name: Build and Publish Frontend Container

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout the repository
      packages: write # To push container image to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        shell: bash
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository }}:latest
